### PR TITLE
Async reddit scraper

### PR DESCRIPTION
**Pull request by pratik-choudhari**
Issue reference #6 
Added async code to reddit scraper for improved execution time.

### CODE REVIEW

**Comment by DarshanDeshpande** [comment]
Any specific reason for sleepinterval to be a list? I feel its very counterintuitive. Also, have you tested the effect of time.sleep on async code? I have a feeling that it will make it more inefficient since it will pause all async tasks that are currently running which might lead to issues with connection establishments

**Comment by pratik-choudhari** [comment]
The sleep interval is a list because I wanted to given the flexibility of setting minimum and maximum sleep seconds by the user. I think you are right about time. sleep, asyncio too has it's own sleep function, I'll check that out

**Comment by DarshanDeshpande** [comment]
Asyncio's sleep function is non blocking so other async activities are still running. This will eventually pop the HTTP 429 Error and there will be no use of sleeping at all. This is the reason why I have removed sleep parameters from my async code as well

**Comment by pratik-choudhari** [comment]
Okay

**Comment by pratik-choudhari** [comment]
@DarshanDeshpande have a look

**Comment by DarshanDeshpande** [comment]
Can you also add rotating proxies with proper error handling? Currently, the code will crash if the random proxy that is chosen is invalid. Instead just delete the proxy from the list and continue till you find a valid one or run out of working proxies

**Comment by pratik-choudhari** [comment]
@DarshanDeshpande

**Comment by DarshanDeshpande** [comment]
Merged. Thanks!

**Pull request merged**
