### PR TITLE
Fixed Code Quality Issues

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description

Summary:

- Use is to compare type of objects
- Remove unnecessary f-string
- Remove unnecessary generator
- Removed multiple import names
- Add .deepsource.toml

I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/Scrapera).

DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to setup DeepSource for Continuous Analysis, I can help you set that up.

### CODE REVIEW

**Comment by HarshCasper** [comment]
Hi @DarshanDeshpande 👋 

Here is the Issue that we had a discussion on: https://github.com/DarshanDeshpande/Scrapera/issues/8 

I have fixed some of the common Issues. Please have a look at the same. Thanks!

**Comment by DarshanDeshpande** [comment]
Merged. Thanks

**Comment by HarshCasper** [comment]
Hi @DarshanDeshpande 

You can now activate Continuous Analysis from the DeepSource Dashboard. Here is a [Blog](https://deepsource.io/blog/setup-static-analysis-python/) that will help to setup continuous analysis on every PR and Commit.

**Comment by DarshanDeshpande** [comment]
I have already done this. Thanks

**Pull request merged**
